name: Deploy

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Cache Maven packages   # ←この行追加
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
          server-id: azisaba
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Prepare settings.xml
        run: |
          echo "<settings><servers><server><id>azisaba</id><username>${{ secrets.REPO_USERNAME }}</username><password>${{ secrets.REPO_PASSWORD }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
      - name: Deploy
        run: mvn deploy
